<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="IT-QA-EMP-02" failures="1" tests="1" name="Default test" time="0.709" errors="0" timestamp="2024-05-15T08:51:22 EET">
  <testcase classname="bankAlEtihadECC.tests.OutwardChequesTest" name="testRun" time="0.683">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void bankAlEtihadECC.tests.OutwardChequesTest.testRun() throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testRun([])
Arguments: [(java.util.HashMap) {Amount1=100, Account Number=0010130830415101, Amount2=80, UserName=SD2023, RunStat=Y, TestCases=Outword Cheques, Cheque Number1=150501, Cheque Number2=150502, URL=https://ecc-uat2.bankaletihad.com/UNION, Password=Test@111}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void bankAlEtihadECC.tests.OutwardChequesTest.testRun() throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testRun([])
Arguments: [(java.util.HashMap) {Amount1=100, Account Number=0010130830415101, Amount2=80, UserName=SD2023, RunStat=Y, TestCases=Outword Cheques, Cheque Number1=150501, Cheque Number2=150502, URL=https://ecc-uat2.bankaletihad.com/UNION, Password=Test@111}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testRun -->
  <testcase classname="bankAlEtihadECC.tests.OutwardChequesTest" name="outwardChequesTest" time="0.0">
    <ignored/>
  </testcase> <!-- outwardChequesTest -->
  <testcase classname="bankAlEtihadECC.tests.OutwardChequesTest" name="repairCheques" time="0.0">
    <ignored/>
  </testcase> <!-- repairCheques -->
</testsuite> <!-- Default test -->
