<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-15T08:51:22 EET" name="Default suite" finished-at="2024-05-15T08:51:22 EET" duration-ms="709">
    <groups>
    </groups>
    <test started-at="2024-05-15T08:51:22 EET" name="Default test" finished-at="2024-05-15T08:51:22 EET" duration-ms="709">
      <class name="bankAlEtihadECC.tests.OutwardChequesTest">
        <test-method signature="testRun()[pri:0, instance:bankAlEtihadECC.tests.OutwardChequesTest@7de843ef]" started-at="2024-05-15T08:51:22 EET" name="testRun" data-provider="getOutwordData" finished-at="2024-05-15T08:51:22 EET" duration-ms="683" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void bankAlEtihadECC.tests.OutwardChequesTest.testRun() throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testRun([])
Arguments: [(java.util.HashMap) {Amount1=100, Account Number=0010130830415101, Amount2=80, UserName=SD2023, RunStat=Y, TestCases=Outword Cheques, Cheque Number1=150501, Cheque Number2=150502, URL=https://ecc-uat2.bankaletihad.com/UNION, Password=Test@111}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void bankAlEtihadECC.tests.OutwardChequesTest.testRun() throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testRun([])
Arguments: [(java.util.HashMap) {Amount1=100, Account Number=0010130830415101, Amount2=80, UserName=SD2023, RunStat=Y, TestCases=Outword Cheques, Cheque Number1=150501, Cheque Number2=150502, URL=https://ecc-uat2.bankaletihad.com/UNION, Password=Test@111}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRun -->
      </class> <!-- bankAlEtihadECC.tests.OutwardChequesTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
